Feat/#220/caching data objects
keeleinstituut/tv-translation-order pull request #2
Opened 2023-06-04 17:26 UTC by kadmit

Task: https://github.com/keeleinstituut/tv-tolkevarav/issues/220

The PR contains the synchronization logic of classifier values, institutions, and institution users.

2023-06-07 20:59 UTC, DanBondarenko requested changes
Hi @kadmit! Thank you for the excellent work in the pull request. The API you created in `SyncTools` really shines through here – abstractions enabling reuse. I look forward to using it in the future.

However, there were a _few_ places where I felt that maybe the abstraction could be reduced somewhat. But then again, maybe the higher level of abstraction will be beneficial later on and it’s too early to judge. 

One place where I had some doubts about the abstraction was the  "gateway" and "api client" layers. They have very similiar responsibilities. In particular, the `get*()` methods (e.g. `getClassifier()`) of the "api client" layer seem to only be used in the corresponding "gateway". So it might make sense to move those methods inside the gateway.

2023-06-07 20:59 UTC, DanBondarenko commented on application/app/Models/ClassifierValue.php
> +
**[blocker]** Correct me if I’m wrong but shouldn’t the schema name come from configuration? I suspect this is the I’m unable to use Tinker for creating these models.

2023-06-07 21:00 UTC, DanBondarenko commented on application/app/Models/InstitutionUser.php
> +    protected $table = 'entity_cache.cached_institution_users';
**[blocker]** https://github.com/keeleinstituut/tv-translation-order/pull/2#discussion_r1222129397

2023-06-08 06:42 UTC, thenouan commented on docker-compose.yml
> +      - 5433:5432
See https://github.com/keeleinstituut/tv-authorization/pull/36#discussion_r1222524945

2023-06-08 06:42 UTC, thenouan commented on docker-compose.yml
> +      - 6378:6379
See https://github.com/keeleinstituut/tv-authorization/pull/36#discussion_r1222524945

2023-06-08 06:43 UTC, thenouan commented on docker-compose.yml
> +      - 6378:6379
Is anyone accessing redis inside host machine network? If not then it doesn't need to be exposed

2023-06-08 06:44 UTC, thenouan commented on application/.env.example
I would use the same .env.example setup as in tv-authorization-service

2023-06-12 10:55 UTC, DanBondarenko commented on docker-compose.yml
> +      - 5433:5432
@kadmit Consider this **[non-blocker]**

2023-06-12 10:56 UTC, DanBondarenko commented on docker-compose.yml
> +      - 6378:6379
@kadmit Consider this **[non-blocker]**

2023-06-12 11:34 UTC, DanBondarenko commented on docker-compose.yml
> +      - 5433:5432
Just for information: I attempted running the tests within the container, but since the database needs to be set up and migrated, I was unable to do it (since `.env.example` specifies port 3306).

<img width="1119" alt="image" src="https://github.com/keeleinstituut/tv-translation-order/assets/26142658/a497100d-db4c-48c6-ad0b-6d05c68c3788">

2023-06-12 11:55 UTC, DanBondarenko commented on docker-compose.yml
> +      - 5433:5432
Just for information: I attempted running the tests within the container, but I encountered some env-related issues: since `.env.example` specifies port 3306, then database setup, migration and tests failed.

![image](https://github.com/keeleinstituut/tv-translation-order/assets/26142658/479146c2-f4c9-4412-bcd9-77a50ff33880)

2023-06-22 12:49 UTC, DanBondarenko commented on application/database/migrations/2023_05_17_112756_create_tags_table.php
> +            $table->foreignUuid('institution_id')->nullable()->constrained('entity_cache.cached_institutions');
Ah, this code was written for [in another pull request](https://github.com/keeleinstituut/tv-translation-order/pull/6) and has already made it to `main` branch, but unfortunately I see that the schema name `entity_cache` has been hardcoded here. Since it’s  configurable via environment variables in other places, seems like it should be the same here.

2023-07-18 04:45 UTC, thenouan approved these changes

2023-07-18 06:20 UTC, merged