Feat/#94,#95,#126,#128/tags crud
keeleinstituut/tv-translation-order pull request #6
Opened 2023-06-09 09:17 UTC by kadmit

Tasks:

- https://github.com/keeleinstituut/tv-tolkevarav/issues/94
- https://github.com/keeleinstituut/tv-tolkevarav/issues/126
- https://github.com/keeleinstituut/tv-tolkevarav/issues/128
- https://github.com/keeleinstituut/tv-tolkevarav/issues/95

Implemented functionalities of updating/deleting/adding/fetching tags.

2023-06-11 21:44 UTC, DanBondarenko requested changes
Thank you for the pull request! 
* I found some opportunities for simplification. I hope you don’t mind that I specified one of them as a "blocker".
* As with https://github.com/keeleinstituut/tv-translation-order/pull/2, I would personally like the `docker-compose.yml`, `phpunit.xml` and `.env.example` to be be "ready" for running tests – right now I had to make changes in order to get tests to run. 
* Also some tests failed for me. Not sure of the reaosn (could also be because of some environment mismatch?). Perhaps you could confirm.

<img width="1372" alt="image" src="https://github.com/keeleinstituut/tv-translation-order/assets/26142658/a1224ca0-8f9b-4aeb-8312-e4a2ac09fd5b">

2023-06-12 08:07 UTC, kadmit commented on application/database/migrations/2023_05_17_112756_create_tags_table.php
> +            $table->foreignUuid('institution_id')->nullable()->constrained('entity_cache.cached_institutions');
@DanBondarenko Based on the requirements the vendor skill tags are the same for all institutions and they are not editable so I made the decision that it makes sense to store them without institution ids instead of producing them for each institution separately.

> Oskused (vendor skills) - this is a tag category that can't be edited by users in phase I, it will be pre-defined list of skills that we display in Sildid (tag's) view. For full pre-configured list see p 2.3

[wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/2.-Klassifikaatorid,-baasfunktsionaalsus-(Klassifikaatorite-haldus-ja-k%C3%B5ige-vajalikumaid-klassifikaatorid)#21-creating-tags)

2023-06-14 09:07 UTC, kadmit commented
@DanBondarenko thank you for such a good review! You pointed out a lot of important things 🙂 I fixed all of them, so please check when you will have time.

Note: We discussed with @thenouan and agreed that initialization of PostgreSQL schemas and users would be better to place into the docker initialization script and the pull request also includes these changes.

2023-06-14 09:51 UTC, thenouan commented on application/app/Policies/TagPolicy.php
> +    }
I'd keep it as is atm. The idea was that "tags" are somewhat comparable to classifiers but the exception is in who's managing them and what's the scope of usage for these

- Classifiers = global, overall system parameters, managed by system administrator
- Tags = within institution, institution-wide parameters, managed internally by some user in institution

From the initial analysis there was a desire that in the future the tags should be configurable by institution, since it is one crucial parameter used to filter suitable vendors for a job and skills may vary from institution to institution

2023-06-14 10:16 UTC, thenouan commented on application/app/Http/Controllers/TagController.php
> +            }
Nothing wrong with this, but wanted to point out that it needs to be refactored when in the future some additional values (e.g. relations) need to be included into representation object, then a querybuilder instance is needed for the saved entities

This can be refactored a little bit as well
```php
$savedObjects = collect($request->validated('data'))->map(function ($input) {
    $entity = new Entity();
    $entity->fill($input);
    $entity->save();
    return $entity;
});
```

2023-06-14 10:16 UTC, thenouan commented on application/app/Http/Controllers/TagController.php
> +        if ($tag->isDirty()) {
This conditional can be omitted, isDirty check is done internally by (new Model)->save() method as well
https://github.com/laravel/framework/blob/5ecbb8797d1affdb764845db31e1e97b0fc9a912/src/Illuminate/Database/Eloquent/Model.php#L1131

2023-06-14 11:04 UTC, DanBondarenko commented
> @DanBondarenko thank you for such a good review! You pointed out a lot of important things 🙂 I fixed all of them, so please check when you will have time.
> 
> Note: We discussed with thenouan and agreed that initialization of PostgreSQL schemas and users would be better to place into the docker initialization script and the pull request also includes these changes.

@kadmit Thank you for the changes and the compliment! Great job ❤️ 

However, unfortunately some environment values are still causing tests to fail. We haven’t agreed upon a "official env for testing", so I totally understand why this can go unnoticed. I don’t want to block progress because of this, but it would be great if you could set the following environment values in either `phpunit.xml` or `.env.example`:

```
DB_HOST=postgres
DB_PORT=5432
DB_USERNAME=user
DB_PASSWORD=pass
```

I am checking whether tests pass by running: 
```
cp application/.env.example application/.env \
&& docker compose up -d --force-recreate \
&& docker compose exec app vendor/bin/phpunit
```

Other than that, looks very nice and you have my approval!

2023-06-14 11:04 UTC, DanBondarenko approved these changes

2023-06-14 12:01 UTC, kadmit commented
@thenouan improved the code according to your recommendations. Thank you for the review 🙂 

@DanBondarenko Fixed the configuration file, thank you for pointing it out.

2023-06-19 06:28 UTC, thenouan approved these changes

2023-06-19 07:31 UTC, merged